[package]
authors = ["DonutLaser <vidmantas.luneckas@gmail.com>"]
edition = "2018"
name = "ralc"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_approx_eq = "1.1.0"
